version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(main)"
    target-branch: "main"
    ignore:
      - dependency-name: org.codehaus.plexus:plexus-utils
        update-types:
          - "version-update:semver-major"
      - dependency-name: org.glassfish.jaxb:jaxb-runtime
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
