language: java
sudo: false
before_script:
  - export MAVEN_SKIP_RC=true
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7
matrix:
  include:
    - addons:
        apt:
          packages:
            - oracle-java7-installer
      jdk: oraclejdk7
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
# skip installation step entirely
install: true
script:
  - mvn -B -V -Prun-its clean verify jacoco:report
after_success:
  # 'coveralls:report' goal is responsible for updating coverall.io stats once travisCI build completes
  # Look for the article 'Coveralls.io configuration for maven projects' in the wiki (https://github.com/asciidoctor/asciidoctor/wiki) for more details
  - mvn coveralls:report
cache:
  directories:
    - $HOME/.m2
