name: Release

on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    environment: release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        java:
          - 11
        maven:
          - 3.9.6
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSS_SONATYPE_USERNAME }}",
              "password": "${{ secrets.OSS_SONATYPE_PASSWORD }}"
            }]
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Configure GPG key
        run: echo -e "${{ env.GPG_PRIVATE_KEY }}" | gpg --import --batch
      - name: Test git
        run: |
          timestamp=$(date +"%Y%m%d-%H%M")
          echo $timestamp > "report-${timestamp}.txt"
          git add .
          git commit -am "Automated report"
          git push
      - name: Build artifacts
        run: mvn -B clean verify -Prelease -Dmaven.test.skip
      - name: Publish artifacts
        run: mvn -B release:prepare release:perform -Darguments="-Prelease -Dmaven.test.skip"
      - name: Close release
        run: |
          echo "Release completed 🎉"
          echo "Remember to "Close" & "Release" at https://oss.sonatype.org"
