name: Release

#on: workflow_dispatch
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  release:
    environment: release
    env:
      GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        java:
          - 11
        maven:
          - 3.9.6
    runs-on: ${{ matrix.os }}
    steps:
      - uses: s4u/setup-maven-action@v1.11.0
        with:
          java-distribution: 'temurin'
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
          settings-servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSS_SONATYPE_USERNAME }}",
              "password": "${{ secrets.OSS_SONATYPE_PASSWORD }}"
            }]
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Configure GPG key
        run: echo -e "${{ env.GPG_PRIVATE_KEY }}" | gpg --import --batch
      - name: Build artifacts
        run: mvn clean verify -B -Prelease -Dmaven.test.skip
      - name: Publish artifacts
        run: mvn release:prepare release:perform -B -Darguments="-Prelease -Dmaven.test.skip"
      - name: Close release
        run: |
          echo "Release completed 🎉"
          echo "Remember to "Close" & "Release" at https://oss.sonatype.org"
