name: Release

on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    environment: release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        java:
          - 11
        maven:
          - 3.9.6
    runs-on: ${{ matrix.os }}
    steps:
      - uses: s4u/setup-maven-action@v1.11.0
        with:
          java-distribution: 'temurin'
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
          settings-servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSS_SONATYPE_USERNAME }}",
              "password": "${{ secrets.OSS_SONATYPE_PASSWORD }}"
            }]
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Prepare key
        run: echo -e "${{ env.GPG_PRIVATE_KEY }}" | gpg --import --batch
      - name: Test git
        run: |
          touch file
          echo "hello" > file
          git add .
          git commit -am "Automated report"
          git push
      - name: Build artifacts
        run: mvn -B clean verify -Prelease -Dmaven.test.skip
      - name: Publish artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B release:prepare release:perform -Darguments="-Prelease -Dmaven.test.skip"
      - name: Close release
        run: |
          echo "Release completed 🎉"
          echo "Remember to "Close" & "Release" at https://oss.sonatype.org"
